name = "real-estate-app"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[functions]
# これがPaidプランの100MB制限を有効にする唯一の指定
limits = { requested_limit = "high" }
